using Content.Client.UserInterface.Controls;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared._Exodus.Territory;
using Content.Shared._Exodus.War;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Exodus.Communications.UI;

[GenerateTypedNameReferences]
public sealed partial class CommunicationsConsoleMenu : FancyWindow
{
    private static readonly Color WarConfirmationTextColor = Color.FromHex("#909090");

    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IGameTiming _timing = default!;

    private readonly Dictionary<ProtoId<TerritoryFactionPrototype>, WarDeclarationRow> _warRows = new();
    private readonly HashSet<ProtoId<TerritoryFactionPrototype>> _seenWarTargets = new();
    private readonly List<ProtoId<TerritoryFactionPrototype>> _staleWarTargets = new();

    private TimeSpan _warAvailableAt;
    private string _warSourceName = string.Empty;
    private long _lastWarCountdownSecond = long.MinValue;
    private bool _hasWarState;
    private bool _warRoundRunning;

    public bool CanAnnounce;
    public bool CanBroadcast;
    public bool AlertLevelSelectable;
    public string CurrentLevel = string.Empty;

    public event Action<string>? OnAlertLevel;
    public event Action<string>? OnAnnounce;
    public event Action<string>? OnBroadcast;
    public event Action<ProtoId<TerritoryFactionPrototype>>? OnDeclareWar;

    public CommunicationsConsoleMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        MessageInput.Placeholder = new Rope.Leaf(_loc.GetString("comms-console-menu-announcement-placeholder"));

        var maxAnnounceLength = _cfg.GetCVar(CCVars.ChatMaxAnnouncementLength);
        MessageInput.OnTextChanged += (args) =>
        {
            if (args.Control.TextLength > maxAnnounceLength)
            {
                AnnounceButton.Disabled = true;
                AnnounceButton.ToolTip = Loc.GetString("comms-console-message-too-long");
            }
            else
            {
                AnnounceButton.Disabled = !CanAnnounce;
                AnnounceButton.ToolTip = null;
            }
        };

        AnnounceButton.OnPressed += _ => OnAnnounce?.Invoke(Rope.Collapse(MessageInput.TextRope));
        AnnounceButton.Disabled = !CanAnnounce;

        BroadcastButton.OnPressed += _ => OnBroadcast?.Invoke(Rope.Collapse(MessageInput.TextRope));
        BroadcastButton.Disabled = !CanBroadcast;

        AlertLevelButton.OnItemSelected += args =>
        {
            var metadata = AlertLevelButton.GetItemMetadata(args.Id);
            if (metadata != null && metadata is string cast)
            {
                OnAlertLevel?.Invoke(cast);
            }
        };

        AlertLevelButton.Disabled = !AlertLevelSelectable;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateWarAvailability();
        UpdateWarConfirmationAppearance();
    }

    public void UpdateWarState(WarDeclarationConsoleState? state)
    {
        _hasWarState = state != null;
        WarSection.Visible = _hasWarState;
        _lastWarCountdownSecond = long.MinValue;

        if (state == null)
        {
            ClearWarRows();
            return;
        }

        _warAvailableAt = state.AvailableAt;
        _warSourceName = Loc.GetString(state.SourceName);
        _warRoundRunning = state.RoundRunning;
        _seenWarTargets.Clear();

        foreach (var target in state.Targets)
        {
            if (!_seenWarTargets.Add(target.Faction))
                continue;

            if (!_warRows.TryGetValue(target.Faction, out var row))
            {
                row = CreateWarRow(target.Faction);
                _warRows.Add(target.Faction, row);
                WarRows.AddChild(row.Container);
            }

            UpdateWarRow(row, target);
        }

        _staleWarTargets.Clear();
        foreach (var faction in _warRows.Keys)
        {
            if (!_seenWarTargets.Contains(faction))
                _staleWarTargets.Add(faction);
        }

        foreach (var faction in _staleWarTargets)
        {
            var row = _warRows[faction];
            row.Container.Dispose();
            _warRows.Remove(faction);
        }

        UpdateWarAvailability();
    }

    private WarDeclarationRow CreateWarRow(ProtoId<TerritoryFactionPrototype> faction)
    {
        var status = new Label
        {
            HorizontalExpand = true,
        };
        var button = new ConfirmButton
        {
            HorizontalExpand = true,
            ResetTime = TimeSpan.FromSeconds(5),
            CooldownTime = TimeSpan.FromSeconds(0.75),
        };
        button.StyleClasses.Add(StyleNano.StyleClassButtonColorRed);
        button.OnPressed += _ => OnDeclareWar?.Invoke(faction);

        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        container.AddChild(status);
        container.AddChild(button);

        return new WarDeclarationRow(container, status, button);
    }

    private void UpdateWarRow(WarDeclarationRow row, WarDeclarationTargetState target)
    {
        var targetName = Loc.GetString(target.Name);
        row.Direction = target.Direction;
        row.Button.ConfirmationText = Loc.GetString(
            "war-declaration-console-confirm",
            ("target", targetName));
        row.Button.Text = Loc.GetString(
            "war-declaration-console-button",
            ("target", targetName));

        switch (target.Direction)
        {
            case WarDeclarationDirection.None:
                row.Status.Text = Loc.GetString(
                    "war-declaration-console-status-cold",
                    ("target", targetName));
                row.Status.FontColorOverride = Color.CornflowerBlue;
                row.Button.Visible = true;
                break;
            case WarDeclarationDirection.Outgoing:
                row.Status.Text = Loc.GetString(
                    "war-declaration-console-status-declared",
                    ("source", _warSourceName),
                    ("target", targetName));
                row.Status.FontColorOverride = Color.Crimson;
                row.Button.Visible = false;
                break;
            case WarDeclarationDirection.Incoming:
                row.Status.Text = Loc.GetString(
                    "war-declaration-console-status-declared",
                    ("source", targetName),
                    ("target", _warSourceName));
                row.Status.FontColorOverride = Color.Crimson;
                row.Button.Visible = false;
                break;
            default:
                throw new ArgumentOutOfRangeException();
        }
    }

    private void UpdateWarAvailability()
    {
        if (!_hasWarState)
            return;

        var secondsRemaining = (long) Math.Ceiling(Math.Max(0, (_warAvailableAt - _timing.CurTime).TotalSeconds));
        if (secondsRemaining == _lastWarCountdownSecond)
            return;

        _lastWarCountdownSecond = secondsRemaining;
        var available = _warRoundRunning && secondsRemaining == 0;
        if (!_warRoundRunning)
        {
            WarUnlockLabel.Text = Loc.GetString("war-declaration-round-not-running");
            WarUnlockLabel.FontColorOverride = Color.Gray;
        }
        else if (available)
        {
            WarUnlockLabel.Text = Loc.GetString("war-declaration-console-available");
            WarUnlockLabel.FontColorOverride = Color.Lime;
        }
        else
        {
            var remaining = TimeSpan.FromSeconds(secondsRemaining);
            var time = $"{(int)remaining.TotalHours:00}:{remaining.Minutes:00}:{remaining.Seconds:00}";
            WarUnlockLabel.Text = Loc.GetString(
                "war-declaration-console-available-in",
                ("time", time));
            WarUnlockLabel.FontColorOverride = Color.Gold;
        }

        foreach (var row in _warRows.Values)
        {
            if (row.Direction != WarDeclarationDirection.None)
                continue;

            if (!available)
                row.Button.Disabled = true;
            else if (!row.Button.IsConfirming)
                row.Button.Disabled = false;
        }
    }

    private void ClearWarRows()
    {
        foreach (var row in _warRows.Values)
        {
            row.Container.Dispose();
        }

        _warRows.Clear();
        _seenWarTargets.Clear();
        _staleWarTargets.Clear();
    }

    private void UpdateWarConfirmationAppearance()
    {
        foreach (var row in _warRows.Values)
        {
            row.Button.Label.FontColorOverride = row.Button.IsConfirming
                ? WarConfirmationTextColor
                : null;
        }
    }

    // The current alert could make levels unselectable, so we need to ensure that the UI reacts properly.
    // If the current alert is unselectable, the only item in the alerts list will be
    // the current alert. Otherwise, it will be the list of alerts, with the current alert
    // selected.
    public void UpdateAlertLevels(List<string>? alerts, string currentAlert)
    {
        AlertLevelButton.Clear();

        if (alerts == null)
        {
            var name = currentAlert;
            if (Loc.TryGetString($"alert-level-{currentAlert}", out var locName))
            {
                name = locName;
            }
            AlertLevelButton.AddItem(name);
            AlertLevelButton.SetItemMetadata(AlertLevelButton.ItemCount - 1, currentAlert);
        }
        else
        {
            foreach (var alert in alerts)
            {
                var name = alert;
                if (Loc.TryGetString($"alert-level-{alert}", out var locName))
                {
                    name = locName;
                }
                AlertLevelButton.AddItem(name);
                AlertLevelButton.SetItemMetadata(AlertLevelButton.ItemCount - 1, alert);
                if (alert == currentAlert)
                {
                    AlertLevelButton.Select(AlertLevelButton.ItemCount - 1);
                }
            }
        }
    }

    private sealed class WarDeclarationRow(
        BoxContainer container,
        Label status,
        ConfirmButton button)
    {
        public BoxContainer Container { get; } = container;
        public Label Status { get; } = status;
        public ConfirmButton Button { get; } = button;
        public WarDeclarationDirection Direction { get; set; }
    }
}
