// Exodus: redesigned cargo order terminal — sidebar categories + dual-pane layout
using System.Linq;
using Content.Client._Exodus.Economy.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.Economy;
using Content.Shared._NF.Bank;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Components;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.Cargo.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CargoConsoleMenu : FancyWindow
    {
        private readonly IEntityManager _entityManager;
        private readonly IPrototypeManager _protoManager;
        private readonly SpriteSystem _spriteSystem;
        private readonly EntityUid _owner;

        public event Action<ButtonEventArgs>? OnItemSelected;
        public event Action<ButtonEventArgs>? OnOrderApproved;
        public event Action<ButtonEventArgs>? OnOrderCanceled;

        /// <summary>
        /// Category keys (prefer loc ids like cargoproduct-category-name-engineering).
        /// Display text is always Loc.GetString(key).
        /// </summary>
        private readonly List<string> _categoryKeys = new();
        private readonly Dictionary<string, Button> _categoryButtons = new();
        private string? _category; // null = All; otherwise normalized category key
        private Dictionary<string, CargoMarketListing>? _marketListings;

        /// <summary>
        /// Legacy bare English categories still found in some YAML → official loc ids.
        /// </summary>
        private static readonly Dictionary<string, string> CategoryAliases =
            new(StringComparer.OrdinalIgnoreCase)
            {
                ["Engineering"] = "cargoproduct-category-name-engineering",
                ["Security"] = "cargoproduct-category-name-security",
                ["Service"] = "cargoproduct-category-name-service",
                ["Medical"] = "cargoproduct-category-name-medical",
                ["Science"] = "cargoproduct-category-name-science",
                ["Food"] = "cargoproduct-category-name-food",
                ["Fun"] = "cargoproduct-category-name-fun",
                ["Hydroponics"] = "cargoproduct-category-name-hydroponics",
                ["Livestock"] = "cargoproduct-category-name-livestock",
                ["Materials"] = "cargoproduct-category-name-materials",
                ["Cargo"] = "cargoproduct-category-name-cargo",
                ["Atmospherics"] = "cargoproduct-category-name-atmospherics",
                ["Emergency"] = "cargoproduct-category-name-emergency",
                ["Shuttle"] = "cargoproduct-category-name-shuttle",
                ["Armory"] = "cargoproduct-category-name-armory",
                ["Circuitboards"] = "cargoproduct-category-name-circuitboards",
            };

        /// <summary>
        /// Normalize prototype.Category to a stable key so Eng/Engineering/loc-id collapse to one tab.
        /// </summary>
        private static string NormalizeCategoryKey(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw))
                return "cargoproduct-category-name-service";

            raw = raw.Trim();

            if (CategoryAliases.TryGetValue(raw, out var aliased))
                return aliased;

            // Already a proper fluent id, or unknown custom id — keep as-is.
            return raw;
        }

        private static string CategoryDisplayName(string key)
        {
            var localized = Loc.GetString(key);
            // Loc returns the key when missing — strip prefix for a cleaner fallback label.
            if (localized == key && key.StartsWith("cargoproduct-category-name-", StringComparison.Ordinal))
                return key["cargoproduct-category-name-".Length..];

            return localized;
        }

        public CargoConsoleMenu(EntityUid owner, IEntityManager entMan, IPrototypeManager protoManager, SpriteSystem spriteSystem)
        {
            RobustXamlLoader.Load(this);
            _entityManager = entMan;
            _protoManager = protoManager;
            _spriteSystem = spriteSystem;
            _owner = owner;

            Title = Loc.GetString("cargo-console-menu-title");

            SearchBar.OnTextChanged += OnSearchBarTextChanged;
            ClearSearchButton.OnPressed += _ =>
            {
                SearchBar.Text = string.Empty;
                PopulateProducts();
            };
        }

        private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
        {
            PopulateProducts();
        }

        private void SelectCategory(string? category)
        {
            _category = category;

            foreach (var (key, button) in _categoryButtons)
            {
                // key "" = All
                var isSelected = category == null
                    ? key.Length == 0
                    : key == category;
                button.Pressed = isSelected;
            }

            PopulateProducts();
        }

        public IEnumerable<CargoProductPrototype> ProductPrototypes
        {
            get
            {
                var allowedGroups = _entityManager.GetComponentOrNull<CargoOrderConsoleComponent>(_owner)?.AllowedGroups;

                foreach (var cargoPrototype in _protoManager.EnumeratePrototypes<CargoProductPrototype>())
                {
                    if (!allowedGroups?.Contains(cargoPrototype.Group) ?? false)
                        continue;

                    yield return cargoPrototype;
                }
            }
        }

        /// <summary>
        /// Live sector market listings from the server (all terminals share one index).
        /// </summary>
        public void SetMarketListings(List<CargoMarketListing>? listings)
        {
            if (listings == null || listings.Count == 0)
            {
                _marketListings = null;
                return;
            }

            var map = new Dictionary<string, CargoMarketListing>(listings.Count);
            foreach (var listing in listings)
            {
                if (listing?.ProductId is not { Length: > 0 } productId)
                    continue;

                map[productId] = listing;
            }

            _marketListings = map.Count > 0 ? map : null;
        }

        public void PopulateProducts()
        {
            Products.RemoveAllChildren();
            var products = ProductPrototypes.ToList();
            products.Sort((x, y) =>
                string.Compare(x.Name, y.Name, StringComparison.CurrentCultureIgnoreCase));

            var search = SearchBar.Text.Trim().ToLowerInvariant();
            var shown = 0;

            foreach (var prototype in products)
            {
                if (!PassesFilters(prototype, search))
                    continue;

                var unitCost = prototype.Cost;
                double? changePercent = null;
                if (_marketListings != null)
                {
                    changePercent = 0;
                    if (_marketListings.TryGetValue(prototype.ID, out var listing))
                    {
                        unitCost = listing.UnitPrice;
                        changePercent = listing.ChangePercent;
                    }
                }

                var button = new CargoProductRow
                {
                    Product = prototype,
                    ProductName = { Text = prototype.Name },
                    MainButton = { ToolTip = prototype.Description },
                    PointCost = { Text = BankSystemExtensions.ToSpesoString(unitCost) },
                    Icon = { Texture = _spriteSystem.Frame0(prototype.Icon) },
                };
                MarketTerminalTheme.ApplyTrendOptional(button.Trend, changePercent);
                button.MainButton.OnPressed += args => OnItemSelected?.Invoke(args);
                Products.AddChild(button);
                shown++;
            }

            ProductCountLabel.Text = Loc.GetString("cargo-console-menu-product-count", ("count", shown));
            CatalogTitleLabel.Text = _category == null
                ? Loc.GetString("cargo-console-menu-catalog-heading")
                : Loc.GetString("cargo-console-menu-catalog-heading-category",
                    ("category", CategoryDisplayName(_category)));
        }

        private bool PassesFilters(CargoProductPrototype prototype, string search)
        {
            if (search.Length != 0)
            {
                return prototype.Name.Contains(search, StringComparison.CurrentCultureIgnoreCase)
                       || prototype.Description.Contains(search, StringComparison.CurrentCultureIgnoreCase);
            }

            if (_category == null)
                return true;

            return NormalizeCategoryKey(prototype.Category) == _category;
        }

        public void PopulateCategories()
        {
            // Rebuild category set without wiping the player's current filter.
            // Keys are normalized loc-ids so "Engineering" and cargoproduct-category-name-engineering merge.
            var next = new List<string>();
            foreach (var prototype in ProductPrototypes)
            {
                var key = NormalizeCategoryKey(prototype.Category);
                if (!next.Contains(key))
                    next.Add(key);
            }

            // Sort by localized display name for the sidebar.
            next.Sort((a, b) =>
                string.Compare(CategoryDisplayName(a), CategoryDisplayName(b),
                    StringComparison.CurrentCultureIgnoreCase));

            var same = next.Count == _categoryKeys.Count;
            if (same)
            {
                for (var i = 0; i < next.Count; i++)
                {
                    if (next[i] != _categoryKeys[i])
                    {
                        same = false;
                        break;
                    }
                }
            }

            if (same && _categoryButtons.Count > 0)
            {
                if (_category != null && !_categoryButtons.ContainsKey(_category))
                    _category = null;

                SyncCategoryPressedState();
                return;
            }

            var previous = _category;
            _categoryKeys.Clear();
            _categoryKeys.AddRange(next);
            _categoryButtons.Clear();
            CategoryListContainer.RemoveAllChildren();

            AddCategoryButton(string.Empty, Loc.GetString("cargo-console-menu-populate-categories-all-text"),
                Loc.GetString("cargo-console-menu-populate-categories-all-text"));

            foreach (var key in _categoryKeys)
            {
                var full = CategoryDisplayName(key);
                AddCategoryButton(key, MarketTerminalTheme.ShortenCategoryLabel(full), full);
            }

            if (previous != null && _categoryButtons.ContainsKey(previous))
                _category = previous;
            else
                _category = null;

            SyncCategoryPressedState();
        }

        private void SyncCategoryPressedState()
        {
            foreach (var (key, button) in _categoryButtons)
            {
                var isSelected = _category == null
                    ? key.Length == 0
                    : key == _category;
                button.Pressed = isSelected;
            }
        }

        private void AddCategoryButton(string key, string label, string? tooltip = null)
        {
            var button = new Button
            {
                Text = label,
                ToggleMode = true,
                Pressed = false,
                HorizontalExpand = true,
                ClipText = true,
                ToolTip = tooltip ?? label,
                StyleClasses = { "ButtonSquare" },
                Margin = new Thickness(0, 0, 0, 1),
            };

            var captured = key;
            button.OnPressed += _ =>
            {
                SelectCategory(captured.Length == 0 ? null : captured);
            };

            _categoryButtons[key] = button;
            CategoryListContainer.AddChild(button);
        }

        public void PopulateOrders(IEnumerable<CargoOrderData> orders)
        {
            Orders.DisposeAllChildren();
            Requests.DisposeAllChildren();

            foreach (var order in orders)
            {
                var product = _protoManager.Index<EntityPrototype>(order.ProductId);
                var productName = product.Name;

                var row = new CargoOrderRow
                {
                    Order = order,
                    Icon = { Texture = _spriteSystem.Frame0(product) },
                    ProductName =
                    {
                        Text = Loc.GetString(
                            "cargo-console-menu-populate-orders-cargo-order-row-product-name-text",
                            ("productName", productName),
                            ("orderAmount", order.OrderQuantity),
                            ("orderRequester", order.Requester))
                    },
                    Description =
                    {
                        Text = Loc.GetString("cargo-console-menu-order-reason-description",
                            ("reason", order.Reason))
                    }
                };
                row.Cancel.OnPressed += args => OnOrderCanceled?.Invoke(args);
                if (order.Approved)
                {
                    row.Approve.Visible = false;
                    row.Cancel.Visible = false;
                    Orders.AddChild(row);
                }
                else
                {
                    row.Approve.OnPressed += args => OnOrderApproved?.Invoke(args);
                    Requests.AddChild(row);
                }
            }
        }

        public void UpdateCargoCapacity(int count, int capacity)
        {
            ShuttleCapacityLabel.Text = $"{count}/{capacity}";
        }

        public void UpdateBankData(string name, int bankBalance)
        {
            AccountNameLabel.Text = name;
            PointsLabel.Text = BankSystemExtensions.ToSpesoString(bankBalance);
        }
    }
}
