using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.Economy; // Exodus appraisal lines
using Content.Shared._NF.Bank;
using Content.Shared.Cargo;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class CargoPalletMenu : FancyWindow
{
    public Action? SellRequested;
    public Action? AppraiseRequested;

    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    private SpriteSystem? _sprite;

    public CargoPalletMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SellButton.OnPressed += OnSellPressed;
        AppraiseButton.OnPressed += OnAppraisePressed;
    }

    public void SetAppraisal(int amount)
    {
        AppraisalLabel.Text = BankSystemExtensions.ToSpesoString(amount);
    }

    public void SetCount(int count)
    {
        CountLabel.Text = count.ToString();
    }

    public void SetTradeCrateMultiplier(double multiplier)
    {
        TradeCrateMultiplierLabel.Text = $"{multiplier:0.00}x";
    }

    public void SetOtherMultiplier(double multiplier)
    {
        OtherMultiplierLabel.Text = $"{multiplier:0.00}x";
    }

    public void SetEnabled(bool enabled)
    {
        AppraiseButton.Disabled = !enabled;
        SellButton.Disabled = !enabled;
    }

    /// <summary>
    /// Exodus: fill scroll list with market-adjusted lines for goods on sell pallets.
    /// </summary>
    public void SetItems(List<CargoPalletAppraisalEntry>? items)
    {
        ItemsList.RemoveAllChildren();

        if (items == null || items.Count == 0)
            return;

        _sprite ??= IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

        foreach (var entry in items)
        {
            var row = new CargoPalletItemRow
            {
                ItemName = { Text = entry.Name },
                Quantity =
                {
                    Text = Loc.GetString("cargo-pallet-menu-item-qty", ("qty", entry.Quantity))
                },
                UnitPrice =
                {
                    Text = Loc.GetString("cargo-pallet-menu-item-unit",
                        ("price", BankSystemExtensions.ToSpesoString(entry.UnitPrice)))
                },
                TotalPrice = { Text = BankSystemExtensions.ToSpesoString(entry.Price) },
            };

            if (entry.PrototypeId != null &&
                _prototypes.TryIndex<EntityPrototype>(entry.PrototypeId, out var proto))
            {
                row.Icon.Texture = _sprite.Frame0(proto);
            }

            ItemsList.AddChild(row);
        }
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }

    private void OnAppraisePressed(BaseButton.ButtonEventArgs obj)
    {
        AppraiseRequested?.Invoke();
    }
}
